window.focusedRecheck=()=>{
 const rows=[];
 const test=(name,fn)=>{try{rows.push({name,result:fn()});}catch(e){rows.push({name,error:e.stack});}};
 test('blackhole_timer_decrements_twice',()=>{const g=resetAudit();const w=new BlackHoleGenerator();w.level=5;const e=dummy(100,0);w.fire(g.player,[e],quietPool());w.timer=999;const before=w.holes[0].tickTimer;w.update(1/60,g.player,[e],quietPool());return {dt:1/60,before,after:w.holes[0].tickTimer,expected:before-1/60};});
 test('single_blackhole_lifetime_hit_times',()=>{const g=resetAudit();g.player.critChance=0;const w=new BlackHoleGenerator();w.level=5;const e=dummy(100,0);const times=[];let t=0;const original=e.takeDamage.bind(e);e.takeDamage=(...args)=>{times.push(+t.toFixed(4));return original(...args);};w.fire(g.player,[e],quietPool());w.timer=999;for(let i=1;i<=220;i++){t=i/60;w.update(1/60,g.player,[e],quietPool());}return {times,hits:times.length,damage:w.damageDealt,declaredInterval:.25,initialDelay:.2,duration:3.4};});
 test('prism_damage_after_expiration',()=>{const g=resetAudit();g.player.critChance=0;const w=new PrismRay();w.level=5;w.evolve();const e=dummy(100,0);w.fire(g.player,[e],quietPool());w.beams=[w.beams[1]];w.beams[0].life=.01;w.beams[0].tickTimer=.05;w.timer=999;w.update(.1,g.player,[e],quietPool());return {remainingLifeBefore:.01,nextTickBefore:.05,dt:.1,damage:w.damageDealt,expectedDamage:0,remainingBeams:w.beams.length};});
 test('drawer_blur_then_close',()=>{const g=resetAudit();g.openBuildDetailModal();window.dispatchEvent(new Event('blur'));const before={state:g.state,reasons:[...g.pauseReasons]};g.closeBuildDetailModal();return {before,after:{state:g.state,reasons:[...g.pauseReasons],pauseModal:document.getElementById('modal-pause').classList.contains('active')}};});
 test('drawer_background_visibility_then_close',()=>{const g=resetAudit();const desc=Object.getOwnPropertyDescriptor(document,'hidden');try{g.openBuildDetailModal();Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));g.closeBuildDetailModal();return {hidden:document.hidden,state:g.state,reasons:[...g.pauseReasons]};}finally{if(desc)Object.defineProperty(document,'hidden',desc);else delete document.hidden;}});
 test('low_priority_evicts_high_priority',()=>{const g=resetAudit();g.isMobileDevice=true;for(let i=0;i<20;i++)g.spawnShockwave(i,0,50,'#ff0055',true);const before=g.shockwaves.filter(s=>s.priority).length;g.spawnShockwave(999,0,20,'#ffffff',false);return {before,afterPriority:g.shockwaves.filter(s=>s.priority).length,ordinary:g.shockwaves.filter(s=>!s.priority).length,total:g.shockwaves.length};});
 test('supernova_priority_flag',()=>{const g=resetAudit();const w=new BlackHoleGenerator();w.level=5;w.evolve();w.triggerSupernova({x:0,y:0,radius:100},g.player,[],g);return {shockwaves:g.shockwaves.map(s=>({priority:s.priority,color:s.color}))};});
 test('boss_hazard_priority_flag',()=>{const g=resetAudit();const b=new BossTitan(400,0,1,g.diffConfig);b.hazardZones=[{x:0,y:0,radius:65,timer:0}];b.update(1/60,g.player,[],[],g);return {shockwaves:g.shockwaves.map(s=>({priority:s.priority,color:s.color}))};});
 test('legitimate_grace_uses_living_player_game_updates',()=>{const g=resetAudit();g.weapons={};g.spawnTimer=999;g.eliteTimer=999;g.bossTime=999;g.openPauseModal();g.resumeGame();const first=g.player.invulnerableTimer;for(let i=0;i<312;i++)g.update(1/60);g.openPauseModal();g.resumeGame();return {first,elapsed:g.elapsedTime,alive:!g.player.isDead,second:g.player.invulnerableTimer,lastGranted:g.lastPauseGraceTime};});
 test('boss_caps_elites_and_pending_deaths',()=>['casual','normal','hard'].map(diff=>{const g=resetAudit(diff);const before=g.stats.kills;g.enemies=Array.from({length:g.diffConfig.maxEnemies},(_,i)=>{const e=new EnemyTypes.RelicGolem(100+i,0);e.isElite=true;return e;});const d=new EnemyTypes.FissionCore(500,0);d.isDead=true;g.enemies.push(d);g.elapsedTime=480;g.updateSpawns(1/60);const atSpawn={living:g.enemies.filter(e=>!e.isDead).length,deadRetained:g.enemies.includes(d),kills:g.stats.kills-before};g.weapons={};g.update(1/60);return {diff,atSpawn,afterUpdate:{kills:g.stats.kills-before,living:g.enemies.filter(e=>!e.isDead).length,crystals:g.crystals.length,hasBoss:!!g.activeBoss}};}));
 test('damage_stats_without_text',()=>{const g=resetAudit();g.player.critChance=0;g.spawnDamageText=()=>{};try{const e=dummy(100,0);e.shieldHp=40;e.hp=43;const w=new PulseBlade();w.level=5;w.calcDamage=()=>({damage:83,isCrit:false});w.fire(g.player,[e],g);w.fire(g.player,[e],g);return {highest:g.stats.highestHit,total:g.stats.totalDamage,weapon:w.damageDealt,kills:w.kills};}finally{delete g.spawnDamageText;}});
 test('tempest_target_sampling',()=>{const g=resetAudit();g.player.critChance=0;const w=new ArcCore();w.level=5;w.evolve();const es=Array.from({length:24},(_,i)=>dummy(i*20,0));es.push(dummy(500,0));es[24].isDead=true;const counts=Array(25).fill(0);let duplicates=0;let hits=new Set();es.forEach((e,i)=>e.takeDamage=()=>{if(hits.has(i))duplicates++;hits.add(i);counts[i]++;return false;});for(let i=0;i<10000;i++){hits.clear();w.fireTempest(g.player,es,quietPool());w.chains=[];}return {counts,duplicates,expectedEachLiving:2500,dead:counts[24]};});
 test('all_evolution_choices_guarantee_and_uniqueness',()=>{const g=resetAudit();for(const w of Object.values(g.weapons))w.level=5;for(const p of Object.values(g.passives))p.level=1;const first={};let failures=0;for(let i=0;i<10000;i++){const cs=g.upgradeSystem.generateChoices(g.weapons,g.passives);if(cs[0].type!=='evolution'||new Set(cs.map(c=>c.targetId)).size!==cs.length)failures++;first[cs[0].targetId]=(first[cs[0].targetId]||0)+1;}return {failures,first};});
 test('sustained_60s_fps',()=>{const out=[];for(const id of Object.keys(WeaponRegistry)){const row={id};for(const fps of [30,60,120,144]){seedRng(12345);const p=new Player(0,0);p.critChance=0;const w=new WeaponRegistry[id]();w.level=5;w.evolve();const e=dummy(100,0);for(let i=0;i<60*fps;i++)w.update(1/fps,p,[e],quietPool());row[fps]=+((w.damageDealt)/60).toFixed(3);}out.push(row);}return out;});
 test('orbital_continuously_overlapping_static_target',()=>[30,60,120,144].map(fps=>{const g=resetAudit();g.player.critChance=0;const w=new OrbitalSatellites();w.level=5;const e=dummy(0,0,200);for(let i=0;i<60*fps;i++)w.update(1/fps,g.player,[e],quietPool());return {fps,seconds:60,totalDamage:w.damageDealt,hits:w.damageDealt/30,dps:w.damageDealt/60};}));
 return rows;
};
window.focusedLayout=()=>{
 const g=resetAudit();g.player.level=35;for(const p of Object.values(g.passives))p.level=5;g.player.recalculateStats(g.passives);g.updateHUD();
 const r=s=>document.querySelector(s).getBoundingClientRect().toJSON();const hit=s=>{const e=document.querySelector(s),b=e.getBoundingClientRect();const points=[[b.left+1,b.top+1],[b.right-1,b.bottom-1],[(b.left+b.right)/2,(b.top+b.bottom)/2]];return {rect:b.toJSON(),hits:points.map(([x,y])=>{const el=document.elementFromPoint(x,y);return !!el&&(e===el||e.contains(el));})};};
 const hud={status:r('.player-status-card'),timer:r('.hud-center'),right:r('.hud-top-right'),pause:hit('#btn-pause'),mute:hit('#btn-mute')};
 document.getElementById('modal-start').classList.add('active');const buttons=[...document.querySelectorAll('.diff-btn')].map(b=>({text:b.textContent,w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height}));document.getElementById('modal-start').classList.remove('active');
 return {viewport:[innerWidth,innerHeight],hud,difficultyButtons:buttons};
};
